import 'server-only';
import { and, asc, eq, gt, isNull, lt, or, sql } from 'drizzle-orm';
import { getDb } from '@/server/db';
// Table objects come from the schema assembly point, not from the owning
// slice's barrel. `@/modules/google` re-exports that slice's client components,
// so importing it here would pull a React client graph into a `server-only`
// query module — and make this file unimportable from a plain Node test. The
// barrel is for *behaviour*; `server/db/schema.ts` is for tables (§2).
import { calendar } from '@/server/db/schema';
import { resolveCategory } from './domain/category';
import { dayKeysOf, expandSeries, isSeries, type Occurrence } from './domain/expand';
import { toDateKey, toWall } from './domain/zone';
import { event, type EventCategory, type EventType } from './schema';

/**
 * Reads for the calendar slice.
 *
 * The one non-obvious thing here is that a stored row is a *series*, not an
 * instance (docs/architecture.md §3). So a read is two steps: fetch the rows
 * that could touch the window, then expand each against it. The database
 * cannot do the second step — RRULE is not a SQL predicate — which is why the
 * `(familyId, startsAt)` index only has to get us to a small candidate set.
 */

/** One rendered instance, everything a view needs and nothing it does not. */
export type CalendarEvent = {
  /** Stable per instance: `seriesId` for a one-off, `seriesId:ISO` otherwise. */
  key: string;
  /** The row this instance came from — what a mutation addresses. */
  seriesId: string;
  title: string;
  description: string | null;
  location: string | null;
  startsAt: Date;
  endsAt: Date;
  allDay: boolean;
  tz: string;
  ownerMemberId: string | null;
  attendeeMemberIds: string[];
  eventType: EventType;
  category: EventCategory;
  calendarId: string | null;
  calendarSummary: string | null;
  /** True when this instance is generated by a rule rather than stored. */
  isRecurringInstance: boolean;
  /** True when the row carries recurrence at all. */
  recurring: boolean;
  /**
   * The stored RRULE, so the edit dialog can preselect the preset that wrote
   * it (and leave an imported rule it cannot represent alone). Null on a
   * redacted event — a rule is detail, and free/busy carries none.
   */
  rrule: string | null;
  /** A push to Google is outstanding — the UI shows a non-blocking pip (§5). */
  pendingSync: boolean;
  /** Detail was withheld: a private calendar rendered free/busy only. */
  busyOnly: boolean;
  /** False for read-only Google calendars and for busy-only instances. */
  editable: boolean;
};

export type EventWindow = { from: Date; to: Date };

export type ListEventsOptions = {
  familyId: string;
  window: EventWindow;
  /**
   * Whether the caller may see *detail* on `visibility: 'private'` calendars.
   * Resolved from `decide(principal, 'calendar:view_private', …)` at the call
   * site — the query does not read a session, so it stays testable and cannot
   * accidentally become a second authorization authority.
   */
  privateDetail: boolean;
};

/** The label a redacted event renders under. Translated at the UI boundary. */
export const BUSY_LABEL = 'busy';

/**
 * Every instance in `[from, to)`, ascending.
 *
 * Candidate selection is deliberately generous on the recurring side: a series
 * that began in 2019 can still produce an instance today, so recurrence rows
 * are fetched whenever they *start* before the window ends, and the expander
 * decides. Non-recurring rows get the tight overlap predicate the index serves.
 */
export async function listEvents(options: ListEventsOptions): Promise<CalendarEvent[]> {
  const { familyId, window, privateDetail } = options;

  const rows = await getDb()
    .select({
      event,
      calendarSummary: calendar.summary,
      calendarColor: calendar.color,
      calendarVisibility: calendar.visibility,
      calendarWritable: calendar.writable,
    })
    .from(event)
    .leftJoin(calendar, eq(event.calendarId, calendar.id))
    .where(
      and(
        eq(event.familyId, familyId),
        isNull(event.deletedAt),
        lt(event.startsAt, window.to),
        or(
          // Recurring rows are expanded, so their stored end says nothing
          // about which instances land in the window.
          isNotEmptyRecurrence(),
          gt(event.endsAt, window.from)
        )
      )
    )
    .orderBy(asc(event.startsAt));

  const events: CalendarEvent[] = [];

  for (const row of rows) {
    const isPrivate = row.calendarVisibility === 'private';
    const redacted = isPrivate && !privateDetail;

    for (const occurrence of expandSeries(row.event, window)) {
      events.push(toCalendarEvent(row, occurrence, redacted));
    }
  }

  return events.sort(
    (a, b) => a.startsAt.getTime() - b.startsAt.getTime() || a.title.localeCompare(b.title)
  );
}

/** `rrule IS NOT NULL OR rdates <> '{}'` — "this row recurs", in SQL. */
function isNotEmptyRecurrence() {
  return or(sql`${event.rrule} is not null`, sql`array_length(${event.rdates}, 1) > 0`);
}

type EventRow = {
  event: typeof event.$inferSelect;
  calendarSummary: string | null;
  calendarColor: string | null;
  calendarVisibility: 'family' | 'private' | null;
  calendarWritable: boolean | null;
};

function toCalendarEvent(row: EventRow, occurrence: Occurrence, redacted: boolean): CalendarEvent {
  const source = row.event;

  return {
    key: occurrence.key,
    seriesId: occurrence.seriesId,
    // Free/busy means exactly that: no title, no description, no location, no
    // location-shaped hints. The block still occupies its slot, which is the
    // whole point of showing it (§7 `calendar:view_private` → `busy-only`).
    title: redacted ? BUSY_LABEL : source.title,
    description: redacted ? null : source.description,
    location: redacted ? null : source.location,
    startsAt: occurrence.startsAt,
    endsAt: occurrence.endsAt,
    allDay: source.allDay,
    tz: source.tz,
    ownerMemberId: source.ownerMemberId,
    attendeeMemberIds: redacted ? [] : source.attendeeMemberIds,
    eventType: source.eventType,
    category: resolveCategory({
      category: source.category,
      calendarColor: row.calendarColor,
    }),
    calendarId: source.calendarId,
    calendarSummary: redacted ? null : row.calendarSummary,
    isRecurringInstance: occurrence.isRecurringInstance,
    recurring: isSeries(source),
    rrule: redacted ? null : source.rrule,
    pendingSync: source.pendingSyncAt !== null,
    busyOnly: redacted,
    // A native event (no calendar) is always ours to edit; a Google one needs
    // a writable calendar. Redacted events are never editable — you cannot
    // meaningfully edit what you are not allowed to read.
    editable: !redacted && (source.calendarId === null || row.calendarWritable === true),
  };
}

/** One row by id, family-scoped. The read behind every event mutation. */
export async function getEvent(familyId: string, eventId: string) {
  const [row] = await getDb()
    .select()
    .from(event)
    .where(and(eq(event.id, eventId), eq(event.familyId, familyId)))
    .limit(1);

  return row ?? null;
}

/** Instances bucketed by `YYYY-MM-DD`, which is how every day-column view reads. */
export function groupByDay(
  events: CalendarEvent[],
  timeZone: string
): Map<string, CalendarEvent[]> {
  const byDay = new Map<string, CalendarEvent[]>();

  for (const item of events) {
    for (const key of dayKeysOf(item, timeZone, item.allDay)) {
      const bucket = byDay.get(key);
      if (bucket) bucket.push(item);
      else byDay.set(key, [item]);
    }
  }

  return byDay;
}

/**
 * Instances bucketed per member, for the per-person column boards (the hub
 * ambient view and `(app)/today`).
 *
 * An event lands in a member's column when they own it *or* attend it. One
 * with neither — "Family dinner" — is household-wide and appears in the
 * `shared` bucket rather than being duplicated into every column, so a wall
 * display does not read as four copies of the same evening.
 */
export function groupByMember(
  events: CalendarEvent[],
  memberIds: string[]
): { byMember: Map<string, CalendarEvent[]>; shared: CalendarEvent[] } {
  const byMember = new Map<string, CalendarEvent[]>(memberIds.map((id) => [id, []]));
  const shared: CalendarEvent[] = [];

  for (const item of events) {
    const owners = new Set<string>();
    if (item.ownerMemberId) owners.add(item.ownerMemberId);
    for (const attendee of item.attendeeMemberIds) owners.add(attendee);

    const targets = [...owners].filter((id) => byMember.has(id));

    if (targets.length === 0) shared.push(item);
    else for (const id of targets) byMember.get(id)!.push(item);
  }

  return { byMember, shared };
}

/** `YYYY-MM-DD` for an instant in a zone — the key `groupByDay` produces. */
export function dayKey(instant: Date, timeZone: string): string {
  return toDateKey(toWall(instant, timeZone));
}
