import 'server-only';
import { and, asc, eq, gt, inArray, isNotNull, isNull, lt, or, sql } from 'drizzle-orm';
import { getDb } from '@/server/db';
// Table objects come from the schema assembly point, not from the owning
// slice's barrel. `@/modules/google` re-exports that slice's client components,
// so importing it here would pull a React client graph into a `server-only`
// query module — and make this file unimportable from a plain Node test. The
// barrel is for *behaviour*; `server/db/schema.ts` is for tables (§2).
import { calendar } from '@/server/db/schema';
import { categoryForType } from './domain/event-type';
import { dayKeysOf, expandSeries, isSeries, type Occurrence } from './domain/expand';
import { toDateKey, toWall } from './domain/zone';
import { event, type EventCategory, type EventType } from './schema';

/**
 * Reads for the calendar slice.
 *
 * The one non-obvious thing here is that a stored row is a *series*, not an
 * instance (docs/architecture.md §3). So a read is two steps: fetch the rows
 * that could touch the window, then expand each against it. The database
 * cannot do the second step — RRULE is not a SQL predicate — which is why the
 * `(familyId, startsAt)` index only has to get us to a small candidate set.
 */

/** One rendered instance, everything a view needs and nothing it does not. */
export type CalendarEvent = {
  /** Stable per instance: `seriesId` for a one-off, `seriesId:ISO` otherwise. */
  key: string;
  /** The row this instance came from — what a mutation addresses. */
  seriesId: string;
  title: string;
  description: string | null;
  location: string | null;
  startsAt: Date;
  endsAt: Date;
  allDay: boolean;
  tz: string;
  ownerMemberId: string | null;
  attendeeMemberIds: string[];
  eventType: EventType;
  /** The hue, a pure function of `eventType` — never stored (M23). */
  category: EventCategory;
  calendarId: string | null;
  calendarSummary: string | null;
  /** True when this instance is generated by a rule rather than stored. */
  isRecurringInstance: boolean;
  /** True when the row carries recurrence at all. */
  recurring: boolean;
  /**
   * The stored RRULE, so the edit dialog can preselect the preset that wrote
   * it (and leave an imported rule it cannot represent alone). Null on a
   * redacted event — a rule is detail, and free/busy carries none.
   */
  rrule: string | null;
  /** A push to Google is outstanding — the UI shows a non-blocking pip (§5). */
  pendingSync: boolean;
  /** Detail was withheld: a private calendar rendered free/busy only. */
  busyOnly: boolean;
  /** False for read-only Google calendars and for busy-only instances. */
  editable: boolean;
};

export type EventWindow = { from: Date; to: Date };

export type ListEventsOptions = {
  familyId: string;
  window: EventWindow;
  /**
   * Whether the caller may see *detail* on `visibility: 'private'` calendars.
   * Resolved from `decide(principal, 'calendar:view_private', …)` at the call
   * site — the query does not read a session, so it stays testable and cannot
   * accidentally become a second authorization authority.
   */
  privateDetail: boolean;
  /**
   * The member whose *own* private calendars stay legible to them (M23).
   *
   * §7 grades `calendar:view_private` `own` for an adult, and `own` is a
   * statement about a concrete resource — which a page-level read has none of,
   * so `decide()` fails closed and the flag above comes back false. Taken
   * literally that means a second parent's private calendar renders as a wall
   * of "bezet" blocks *to her*, unclickable, which is neither what the matrix
   * says nor anything a household would ask for.
   *
   * So the `own` grade is carried here instead of being collapsed at the call
   * site: the resource it needs is `calendar.owner_member_id`, and only this
   * query is holding one. Null (and every non-member principal) keeps the
   * old, strict behaviour.
   */
  privateDetailFor?: string | null;
};

/** The label a redacted event renders under. Translated at the UI boundary. */
export const BUSY_LABEL = 'busy';

/**
 * Every instance in `[from, to)`, ascending.
 *
 * Candidate selection is deliberately generous on the recurring side: a series
 * that began in 2019 can still produce an instance today, so recurrence rows
 * are fetched whenever they *start* before the window ends, and the expander
 * decides. Non-recurring rows get the tight overlap predicate the index serves.
 */
export async function listEvents(options: ListEventsOptions): Promise<CalendarEvent[]> {
  const { familyId, window, privateDetail, privateDetailFor = null } = options;

  const rows = await getDb()
    .select({
      event,
      calendarSummary: calendar.summary,
      calendarVisibility: calendar.visibility,
      calendarWritable: calendar.writable,
      calendarOwnerMemberId: calendar.ownerMemberId,
    })
    .from(event)
    .leftJoin(calendar, eq(event.calendarId, calendar.id))
    .where(
      and(
        eq(event.familyId, familyId),
        isNull(event.deletedAt),
        /**
         * M18 safety net: a calendar with sync switched off shows nothing.
         *
         * The *mechanism* is in `modules/google/actions.ts` — disabling a
         * calendar deletes its events and clears its cursor in one
         * transaction, so in the ordinary case there is nothing here to
         * filter. This predicate covers the gap that mechanism cannot: a row
         * that arrives from a sync pass racing the disable, or from any future
         * write path that forgets the rule. One `AND` on a query that already
         * joins `calendar`, against a class of bug whose symptom is a
         * household's colleague's diary reappearing on their kitchen wall.
         *
         * The `isNull` arm is load-bearing: a Kynite-native event has no
         * calendar row at all, and the `leftJoin` gives it a null
         * `syncEnabled`, which a bare `eq(calendar.syncEnabled, true)` would
         * read as "off" and hide every locally-created event in the app.
         */
        or(isNull(event.calendarId), eq(calendar.syncEnabled, true)),
        lt(event.startsAt, window.to),
        or(
          // Recurring rows are expanded, so their stored end says nothing
          // about which instances land in the window.
          isNotEmptyRecurrence(),
          gt(event.endsAt, window.from)
        )
      )
    )
    .orderBy(asc(event.startsAt));

  // Only a row that recurs can generate a slot an override needs to take back,
  // so the lookup is asked about those and nothing else.
  const exceptions = await overrideStartsByParent(
    rows.filter((row) => isSeries(row.event)).map((row) => row.event.id)
  );

  const events: CalendarEvent[] = [];

  for (const row of rows) {
    const isPrivate = row.calendarVisibility === 'private';
    // "Own" beats "private": a calendar's own member always reads their own
    // detail, whatever the surface-level flag says.
    const ownPrivate = privateDetailFor !== null && row.calendarOwnerMemberId === privateDetailFor;
    const redacted = isPrivate && !privateDetail && !ownPrivate;

    for (const occurrence of expandSeries(row.event, {
      ...window,
      excludeStarts: exceptions.get(row.event.id),
    })) {
      events.push(toCalendarEvent(row, occurrence, redacted));
    }
  }

  return events.sort(
    (a, b) => a.startsAt.getTime() - b.startsAt.getTime() || a.title.localeCompare(b.title)
  );
}

/**
 * The slots imported overrides take out of their parent series.
 *
 * Google does not write an EXDATE onto a master when one of its occurrences is
 * edited — it sends a separate instance resource carrying `originalStartTime`,
 * which sync stores as `recurrenceOriginalStart`. Without subtracting those the
 * parent generates the occurrence *and* the child row renders it, which is the
 * duplicate every recurring Google event showed on the board.
 *
 * Two deliberate details:
 *
 * - **Soft-deleted children count.** An override Google later cancelled means
 *   that occurrence is gone, not that the original slot comes back.
 * - **A null `recurrenceOriginalStart` subtracts nothing.** The obvious guess —
 *   fall back to the child's own start — is wrong for the one case it would
 *   have to be right about: an occurrence that was *moved*. A "this occurrence
 *   only" drag lands the child on a different instant, and subtracting that
 *   instant deletes whichever occurrence the series legitimately generates
 *   there (a daily event moved to tomorrow, a weekly one moved a week). Nor is
 *   `google_event_id IS NULL` a way to spot a native override and dodge it:
 *   `pushStore.claimGoogleEventId` stamps an id on a Kynite-authored child
 *   before it is even inserted. Rows imported before the column existed are
 *   repaired at the source instead — `needsExceptionBackfill` in the sync
 *   engine writes the real `originalStartTime` through echo suppression on the
 *   full pass `drizzle/0018` forces.
 */
async function overrideStartsByParent(parentIds: string[]): Promise<Map<string, Date[]>> {
  const byParent = new Map<string, Date[]>();
  if (parentIds.length === 0) return byParent;

  const rows = await getDb()
    .select({ parentId: event.recurrenceParentId, originalStart: event.recurrenceOriginalStart })
    .from(event)
    .where(
      and(inArray(event.recurrenceParentId, parentIds), isNotNull(event.recurrenceOriginalStart))
    );

  for (const row of rows) {
    if (!row.parentId || !row.originalStart) continue;

    const slots = byParent.get(row.parentId);
    if (slots) slots.push(row.originalStart);
    else byParent.set(row.parentId, [row.originalStart]);
  }

  return byParent;
}

/** `rrule IS NOT NULL OR rdates <> '{}'` — "this row recurs", in SQL. */
function isNotEmptyRecurrence() {
  return or(sql`${event.rrule} is not null`, sql`array_length(${event.rdates}, 1) > 0`);
}

type EventRow = {
  event: typeof event.$inferSelect;
  calendarSummary: string | null;
  calendarVisibility: 'family' | 'private' | null;
  calendarWritable: boolean | null;
  calendarOwnerMemberId: string | null;
};

function toCalendarEvent(row: EventRow, occurrence: Occurrence, redacted: boolean): CalendarEvent {
  const source = row.event;

  return {
    key: occurrence.key,
    seriesId: occurrence.seriesId,
    // Free/busy means exactly that: no title, no description, no location, no
    // location-shaped hints. The block still occupies its slot, which is the
    // whole point of showing it (§7 `calendar:view_private` → `busy-only`).
    title: redacted ? BUSY_LABEL : source.title,
    description: redacted ? null : source.description,
    location: redacted ? null : source.location,
    startsAt: occurrence.startsAt,
    endsAt: occurrence.endsAt,
    allDay: source.allDay,
    tz: source.tz,
    ownerMemberId: source.ownerMemberId,
    attendeeMemberIds: redacted ? [] : source.attendeeMemberIds,
    eventType: source.eventType,
    // The whole colouring policy (M23): the hue is a function of the type, on
    // every surface, resolved once here so no view has to.
    category: categoryForType(source.eventType),
    calendarId: source.calendarId,
    calendarSummary: redacted ? null : row.calendarSummary,
    isRecurringInstance: occurrence.isRecurringInstance,
    recurring: isSeries(source),
    rrule: redacted ? null : source.rrule,
    pendingSync: source.pendingSyncAt !== null,
    busyOnly: redacted,
    // A native event (no calendar) is always ours to edit; a Google one needs
    // a writable calendar. Redacted events are never editable — you cannot
    // meaningfully edit what you are not allowed to read.
    editable: !redacted && (source.calendarId === null || row.calendarWritable === true),
  };
}

/** One row by id, family-scoped. The read behind every event mutation. */
export async function getEvent(familyId: string, eventId: string) {
  const [row] = await getDb()
    .select()
    .from(event)
    .where(and(eq(event.id, eventId), eq(event.familyId, familyId)))
    .limit(1);

  return row ?? null;
}

/** Instances bucketed by `YYYY-MM-DD`, which is how every day-column view reads. */
export function groupByDay(
  events: CalendarEvent[],
  timeZone: string
): Map<string, CalendarEvent[]> {
  const byDay = new Map<string, CalendarEvent[]>();

  for (const item of events) {
    for (const key of dayKeysOf(item, timeZone, item.allDay)) {
      const bucket = byDay.get(key);
      if (bucket) bucket.push(item);
      else byDay.set(key, [item]);
    }
  }

  return byDay;
}

/**
 * Instances bucketed per member, for the per-person column boards (the hub
 * ambient view and `(app)/today`).
 *
 * An event lands in a member's column when they own it *or* attend it. One
 * with neither — "Family dinner" — is household-wide and appears in the
 * `shared` bucket rather than being duplicated into every column, so a wall
 * display does not read as four copies of the same evening.
 */
export function groupByMember(
  events: CalendarEvent[],
  memberIds: string[]
): { byMember: Map<string, CalendarEvent[]>; shared: CalendarEvent[] } {
  const byMember = new Map<string, CalendarEvent[]>(memberIds.map((id) => [id, []]));
  const shared: CalendarEvent[] = [];

  for (const item of events) {
    const owners = new Set<string>();
    if (item.ownerMemberId) owners.add(item.ownerMemberId);
    for (const attendee of item.attendeeMemberIds) owners.add(attendee);

    const targets = [...owners].filter((id) => byMember.has(id));

    if (targets.length === 0) shared.push(item);
    else for (const id of targets) byMember.get(id)!.push(item);
  }

  return { byMember, shared };
}

/** `YYYY-MM-DD` for an instant in a zone — the key `groupByDay` produces. */
export function dayKey(instant: Date, timeZone: string): string {
  return toDateKey(toWall(instant, timeZone));
}
