/* THIS FILE IS AUTO-GENERATED BY PAYLOAD CMS */
/* DO NOT MODIFY IT MANUALLY - RUN `pnpm dev` TO REGENERATE */

/**
 * Placeholder types for Payload CMS collections.
 * These will be replaced with accurate types when Payload runs.
 */

export interface User {
  id: string;
  email: string;
  name?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Media {
  id: string;
  alt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface Page {
  id: string;
  title: string;
  slug: string;
  status?: "draft" | "published" | null;
  content?: unknown;
  layout?: (HeroBlock | FeaturesBlock | PricingBlock | CtaBlock)[] | null;
  meta?: {
    description?: string | null;
    image?: string | Media | null;
  };
  createdAt: string;
  updatedAt: string;
}

export interface HeroBlock {
  blockType: "hero";
  badge?: string | null;
  title: string;
  description: string;
  primaryCta?: {
    label: string;
    href: string;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  previewLabel?: string | null;
}

export interface FeaturesBlock {
  blockType: "features";
  title: string;
  subtitle?: string | null;
  features?: {
    icon: string;
    title: string;
    description: string;
  }[];
}

export interface PricingBlock {
  blockType: "pricing";
  title: string;
  subtitle?: string | null;
  tiers?: {
    name: string;
    price: number;
    currency?: string | null;
    period?: string | null;
    description?: string | null;
    featured?: boolean | null;
    features?: { text: string }[];
    cta?: {
      label: string;
      href: string;
    };
  }[];
}

export interface CtaBlock {
  blockType: "cta";
  title: string;
  description?: string | null;
  button?: {
    label: string;
    href: string;
    variant?: "default" | "secondary" | "outline" | null;
  };
}

export interface Config {
  collections: {
    users: User;
    media: Media;
    pages: Page;
  };
}
