/**
 * GENERATED by scripts/subset-icons.mjs — do not edit.
 *
 * Material Symbols renders here by codepoint, not by ligature; see that script
 * for why. Every entry has a matching glyph in
 * src/styles/fonts/material-symbols-outlined.woff2, which `pnpm icons:check`
 * verifies against actual `<Icon name="…">` usage on every build.
 */

export const ICON_CODEPOINTS = {
  add: '\ue145',
  arrow_downward: '\ue5db',
  arrow_upward: '\ue5d8',
  cake: '\ue7e9',
  calendar_month: '\uebcc',
  check: '\ue668',
  checklist: '\ue6b1',
  chevron_left: '\ue5cb',
  chevron_right: '\ue5cc',
  cookie: '\ueaac',
  dark_mode: '\ue51c',
  dashboard: '\ue871',
  delete: '\ue92e',
  diversity_3: '\uf8d9',
  event: '\ue878',
  event_available: '\ue614',
  family_home: '\ueb26',
  family_restroom: '\uf1a2',
  hourglass_top: '\uea5b',
  icecream: '\uea69',
  label: '\ue893',
  light_mode: '\ue518',
  local_fire_department: '\uef55',
  location_on: '\uf1db',
  menu_book: '\uea19',
  movie: '\ue684',
  notifications: '\ue7f5',
  palette: '\ue40a',
  park: '\uea63',
  pets: '\ue91d',
  pool: '\ueb48',
  redeem: '\ue8f6',
  repeat: '\ue040',
  restaurant: '\ue56c',
  schedule: '\uefd6',
  settings: '\ue8b8',
  sports_esports: '\uea28',
  star: '\uf09a',
  task_alt: '\ue2e6',
  timer: '\ue425',
  wb_sunny: '\ue430',
  workspace_premium: '\ue7af',
} as const;

export type IconName = keyof typeof ICON_CODEPOINTS;
